import Head from 'next/head'
import { useState } from 'react';
import { AiOutlinePlusCircle, AiOutlineDelete, AiOutlineEdit } from 'react-icons/ai'

import TextInput from '../components/todoInput';
import TodoListContainer from './../components/todoListContainer';
import TodoText from './../components/todoText';

// Change SSR to SSG

export async function getStaticProps(context) {
  const res = [];
  return {
    props: { data: res }, // will be passed to the page component as props
  }
}

const Home = ({ data }) => {
  const [todo, setTodo] = useState("")

  const handleAddTodo = () => {
    console.log("todo added");
  }

  const handleDelete = () => {
    console.log("todo deleted");
  }

  const handleEdit = () => {
    console.log("todo edited");
  }

  return (
    <>
      <Head>
        <title>TodoList App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoListContainer>
        <TextInput variant="standard" placeholder="add new todo" value={todo}
          onChange={(e) => setTodo(e.target.value)}
          inputIcon={<AiOutlinePlusCircle onClick={handleAddTodo} />} />

        <TodoText todoText="buy bread" checked={false} onClick={(e) => console.log(e.target)}
          todoIcon={<><AiOutlineDelete onClick={handleDelete} /><AiOutlineEdit onClick={handleEdit} /></>} />

      </TodoListContainer>
    </>
  )
}

export default Home